name: "keep a changelog"
on:
  release:
    types: [published]

jobs:
  update-changelog:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Update changelog
      uses: thomaseizinger/keep-a-changelog-new-release@v1
      with:
        version: $GITHUB_REF
        
    - name: push changelog.md
      run: |
        git status
        git diff CHANGELOG.md
        git describe --tags
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git switch -c update-changelog
        git add CHANGELOG.md
        git commit -m "CHANGELOG.md updated"
        git push --set-upstream origin update-changelog
        git branch -d update-changelog
      working-directory: ./
